### PR TITLE
Change CRD domain to spinkube.dev

### PR DESCRIPTION
**Pull request by adamreese**
REF:
https://github.com/spinkube/skips/pull/5
https://github.com/spinkube/spin-operator/pull/271

### CODE REVIEW

**Comment by calebschoepp** [comment]
@bacongobbler your eyeballs would be greatly appreciated in this general direction.

**Review by Mossaka — APPROVED** [review]
lgtm!

**Comment by calebschoepp** [comment]
Since we release docs off the tip of main I've marked this PR as DO NOT MERGE until we release spin operator v0.4.0

**Comment by bacongobbler** [comment]
force-pushed the commit to sign off on it

**Pull request merged**
